import type { Metadata } from "next";

import { PageHero } from "@/components/ui/PageHero";
import { ContentBlocks } from "@/components/ui/ContentBlocks";
import { company } from "@/lib/data/company";

export const metadata: Metadata = {
  title: "Privacy Policy — Scantech Info Systems",
  description:
    "How Scantech Info Systems handles personal and business data: what this website collects, what we receive when you contact us, how long it is kept and your rights.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow="Privacy & Data"
        title="Privacy Policy"
        lede="What this website collects, what we receive when you contact us, how it is stored, and how to have it removed."
        crumbs={[{ label: "Home", href: "/" }, { label: "Privacy Policy" }]}
        note={`Last updated ${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long" })}`}
      />

      <ContentBlocks
        blocks={[
          {
            kind: "prose",
            heading: "Summary",
            tone: "white",
            paragraphs: [
              "This website is a read-only information site. It has no contact form, no booking system, no newsletter, no user accounts and no advertising. We do not ask you for personal information anywhere on it, and we do not build a profile of you.",
              "We do receive personal and business information when you choose to phone or email us. That is covered below, along with what we do with it.",
            ],
          },
          {
            kind: "bullets",
            heading: "What this website collects",
            tone: "low",
            columns: 1,
            items: [
              "Standard server logs — the page requested, the time, the referring page and the browser or device type. These are generated by the hosting infrastructure for security and reliability purposes.",
              "No cookies are set by this website for tracking, advertising or profiling.",
              "No third-party analytics, advertising pixel or social media tracker is loaded by this website.",
              "No account creation, no login and no user-generated content.",
            ],
          },
          {
            kind: "prose",
            heading: "Information you give us when you contact us",
            tone: "white",
            paragraphs: [
              "When you call or email Scantech you will usually give us your name, organisation, contact details and a description of your requirement or fault. If you become a customer, we also hold commercial and service records — quotations, contracts, asset registers, service history and invoicing details.",
              "We use that information only for the purpose you gave it to us: responding to your enquiry, supplying and supporting the equipment and services you have asked for, and meeting our contractual and statutory obligations. We do not sell it, rent it or trade it.",
            ],
          },
          {
            kind: "prose",
            heading: "Who we share it with",
            tone: "low",
            paragraphs: [
              "Information is shared only where it is necessary to deliver what you asked for — for example with a manufacturer or authorised distributor when a warranty claim or a spare part has to be raised against your equipment, or with a courier delivering to your site.",
              "We may also disclose information where we are legally required to do so, for example in response to a lawful request from a court, a tax authority or a regulatory body.",
            ],
          },
          {
            kind: "prose",
            heading: "How long we keep it",
            tone: "white",
            paragraphs: [
              "Enquiries that do not become business are kept only as long as they are useful for answering you, and are then discarded. Customer contract, service and invoicing records are retained for the period required by Indian tax and commercial law, and for as long as is necessary to support warranty and service obligations on the equipment we have supplied.",
            ],
          },
          {
            kind: "prose",
            heading: "How it is protected",
            tone: "low",
            paragraphs: [
              "Access to customer records is limited to the staff who need it to do their job — service, contracts and accounts. Records are held on systems with access control, and paper records are held at our Masab Tank office.",
            ],
          },
          {
            kind: "bullets",
            heading: "Your choices",
            tone: "white",
            columns: 1,
            items: [
              "Ask us what information we hold about you or your organisation.",
              "Ask us to correct anything that is wrong.",
              "Ask us to delete information we are not required to keep for legal or contractual reasons.",
              "Ask us to stop contacting you about anything other than work you have asked us to do.",
              "Ask us which manufacturer or distributor your information was passed to, and for what purpose.",
            ],
          },
          {
            kind: "prose",
            heading: "Contacting us about privacy",
            tone: "low",
            paragraphs: [
              `Write to ${company.email} or call ${company.phoneDisplay}. Address privacy requests to the head office at ${company.addressLine}. Tell us what you are asking for and we will respond in writing.`,
            ],
          },
          {
            kind: "prose",
            heading: "Changes to this policy",
            tone: "white",
            paragraphs: [
              "If this policy changes, the revision date at the top of this page changes with it. If we ever introduce something that collects information — a working enquiry form, or analytics — this page will be updated before that happens, not after.",
            ],
          },
          {
            kind: "cta",
            heading: "Questions about how we handle your data?",
            body: "Ask us directly. For a business like ours the honest answer is usually a short one, and we would rather give it than have you infer it from a policy.",
            primary: { label: "Contact Scantech", href: "/contact" },
            secondary: { label: "Read the terms", href: "/terms" },
          },
        ]}
      />
    </>
  );
}
